force-app/main/default/objects/GGW_Content_Block__c/GGW_Content_Block__c.object-meta.xml
<CustomObject>
    <description>Block of content, text with attributes used in Grant application</description>
    <label>Content Block</label>
    <nameField>
        <label>Content Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/default/objects/GGW_Content_Block__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Main formatted rich text holds a block of content</description>
    <inlineHelpText>Main formatted rich text holds a block of content</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/default/objects/GGW_Content_Block__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related parent Section record</description>
    <inlineHelpText>Related parent Section record</inlineHelpText>
    <label>Section</label>
    <referenceTo>GGW_Section__c</referenceTo>
    <relationshipLabel>Content Blocks</relationshipLabel>
    <relationshipName>Content_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/default/objects/GGW_Content_Block__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <description>Short text for search or tags identify content block</description>
    <inlineHelpText>Short text for search or tags identify content block</inlineHelpText>
    <label>Short Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/default/objects/GGW_Section__c/GGW_Section__c.object-meta.xml
<CustomObject>
    <description>Dynamic Sections</description>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GGW_ContentBlockSelector.cls
/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 * 
 * GGW_ContentBlockSelector Salesforce Content Block text data selector class support GGW.
 * 
 */
public with sharing class GGW_ContentBlockSelector {
    public static GGW_Content_Block__c queryContentBlockById(Id blockId){
        GGW_Content_Block__c cBlock = [SELECT Id, Name, Description__c 
                                        FROM GGW_Content_Block__c 
                                        WHERE Id =: blockId WITH SECURITY_ENFORCED LIMIT 1];
        return cBlock;
    }
    public static List<GGW_Content_Block__c> queryContentBlocksBySection(Id sectionId){
        List<GGW_Content_Block__c> cbList = [SELECT Id, Name, Description__c, Short_Description__c, 
                                                Section__c, Section__r.Name, CreatedDate, 
                                                Language__c  
                                                FROM GGW_Content_Block__c 
                                                WHERE Section__c =: sectionId WITH SECURITY_ENFORCED];
        return cbList;
    }
    public static List<GGW_Content_Block__c> queryContentBlocks(){
        List<GGW_Content_Block__c> cbList = [SELECT Id, Name, Description__c, Short_Description__c, 
                                                Section__c, Section__r.Name, CreatedDate, 
                                                Language__c 
                                            FROM GGW_Content_Block__c WITH SECURITY_ENFORCED ORDER BY Section__c];
        return cbList;
    }
}