force-app/main/default/objects/GGW_Content_Block__c/GGW_Content_Block__c.object-meta.xml
<CustomObject>
    <description>Block of content, text with attributes used in Grant application</description>
    <label>Content Block</label>
    <nameField>
        <label>Content Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/default/objects/GGW_Content_Block__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Main formatted rich text holds a block of content</description>
    <inlineHelpText>Main formatted rich text holds a block of content</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/default/objects/GGW_Grant_Application__c/GGW_Grant_Application__c.object-meta.xml
<CustomObject>
    <description>Main header object to manage and create Grant applications and related content</description>
    <label>Grant Application</label>
    <nameField>
        <label>GGW Grant Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/n/GGW_Grant_Editor?c__recordId=&quot; &amp; Id, Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describe a grant in short text with 255 characters</description>
    <inlineHelpText>Describe a grant in short text with 255 characters</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language_Support</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/default/objects/GGW_Section__c/GGW_Section__c.object-meta.xml
<CustomObject>
    <description>Dynamic Sections</description>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GGW_Section__c/fields/Recommended__c.field-meta.xml
<CustomField>
    <fullName>Recommended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GGW_Section__c/fields/Suggested__c.field-meta.xml
<CustomField>
    <fullName>Suggested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suggested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/default/objects/GGW_Selected_Item__c/GGW_Selected_Item__c.object-meta.xml
<CustomObject>
    <description>Junction link for Grant application and content blocks</description>
    <label>Selected Item</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <formula>Grant_Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/GGW_Section__c.field-meta.xml
<CustomField>
    <fullName>GGW_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to section</description>
    <inlineHelpText>Link to section</inlineHelpText>
    <label>Section</label>
    <referenceTo>GGW_Section__c</referenceTo>
    <relationshipLabel>Selected Items</relationshipLabel>
    <relationshipName>Selected_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Grant_Application__c.field-meta.xml
<CustomField>
    <fullName>Grant_Application__c</fullName>
    <description>Grant Application master record</description>
    <inlineHelpText>Grant Application master record parent</inlineHelpText>
    <label>Grant Application</label>
    <referenceTo>GGW_Grant_Application__c</referenceTo>
    <relationshipLabel>Selected Items</relationshipLabel>
    <relationshipName>Selected_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <formula>TEXT(Grant_Application__r.Language__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/default/objects/GGW_Selected_Item__c/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <formula>GGW_Section__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Section Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Selected_Block__c.field-meta.xml
<CustomField>
    <fullName>Selected_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to a chose text block for section to use in Grant application</description>
    <inlineHelpText>Link to a chose text block for section to use in Grant application</inlineHelpText>
    <label>Selected Block</label>
    <referenceTo>GGW_Content_Block__c</referenceTo>
    <relationshipLabel>Selected Items</relationshipLabel>
    <relationshipName>Selected_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/default/objects/GGW_Selected_Item__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Text_Block__c.field-meta.xml
<CustomField>
    <fullName>Text_Block__c</fullName>
    <description>Formatted rich text holds a copy of block of content or new content for editing and grant.</description>
    <inlineHelpText>Formatted rich text holds a copy of block of content or new content for editing and grant.</inlineHelpText>
    <label>Text Block</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/Language_Support.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <description>Supported languages to switch</description>
    <masterLabel>Language Support</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GGW_SectionSelector.cls
/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 * 
 * GGW_ContentSelector Grant Section data selector class support GGW.
 * 
 */
public with sharing class GGW_SectionSelector {
    public static List<GGW_Selected_Item__c> querySelectedItemsByGrant(String appId){
        List<GGW_Selected_Item__c> appItems = [SELECT Id, Application_Name__c, Grant_Application__c, GGW_Section__c, 
                                    Section_Name__c,Selected_Block__c, Sort_Order__c, Grant_Application__r.Status__c,
                                    Selected_Block__r.Description__c, Text_Block__c, Language__c 
                                    FROM GGW_Selected_Item__c 
                                    WHERE Grant_Application__c =: appId WITH SECURITY_ENFORCED ORDER BY Sort_Order__c];
        return appItems;
    }
    
    public static List<GGW_Section__c> querySectionsByLanguage(String lang){
        List<GGW_Section__c> sectionList = [SELECT Id, Name, CreatedDate, Recommended__c, Suggested__c, 
                                                Sort_Order__c, Language__c 
                                            FROM GGW_Section__c 
                                            WHERE Suggested__c = true AND Language__c =: lang 
                                            WITH SECURITY_ENFORCED ORDER BY Sort_Order__c];
        return sectionList;
    }
    public static List<GGW_Section__c> querySections(){
        List<GGW_Section__c> sectionList = [SELECT Id, Name, CreatedDate, Recommended__c, Suggested__c, 
                                                    Sort_Order__c, Language__c 
                                            FROM GGW_Section__c WITH SECURITY_ENFORCED ORDER BY Sort_Order__c];
        return sectionList;
    }
    public static List<GGW_Section__c> querySectionsByName(String searchKey){
        String key = '%' + searchKey + '%';
        List<GGW_Section__c> sectionList = [SELECT Id, Name, CreatedDate, Recommended__c, Suggested__c, 
                                                    Sort_Order__c, Language__c 
                                            FROM GGW_Section__c 
                                            WHERE Name LIKE :key AND Suggested__c = false 
                                            WITH SECURITY_ENFORCED ORDER BY Sort_Order__c LIMIT 20];
        return sectionList;
    }
    // Return section with max order to add next section
    public static GGW_Section__c findMaxOrderSection(){
        List<GGW_Section__c> maxOrderList = [SELECT Sort_Order__c 
                                                    FROM GGW_Section__c 
                                                    WHERE Suggested__c = true WITH SECURITY_ENFORCED ORDER BY Sort_Order__c desc];
        GGW_Section__c maxOrder = null;
            // Handle situation when Sort order is null - TODO MAY be good to require it
        for(GGW_Section__c section : maxOrderList ){
            if(section.Sort_Order__c != null && section.Sort_Order__c > 0){
                maxOrder = section; // assigned MAX order object first found END LOOP here
                break; // EXIT Loop
            }
        }
        return maxOrder;
    }
    
}