force-app/main/default/default/objects/GGW_Section__c/GGW_Section__c.object-meta.xml
<CustomObject>
    <description>Dynamic Sections</description>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/default/objects/GGW_Selected_Item__c/GGW_Selected_Item__c.object-meta.xml
<CustomObject>
    <description>Junction link for Grant application and content blocks</description>
    <label>Selected Item</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <formula>Grant_Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/GGW_Section__c.field-meta.xml
<CustomField>
    <fullName>GGW_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to section</description>
    <inlineHelpText>Link to section</inlineHelpText>
    <label>Section</label>
    <referenceTo>GGW_Section__c</referenceTo>
    <relationshipLabel>Selected Items</relationshipLabel>
    <relationshipName>Selected_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Grant_Application__c.field-meta.xml
<CustomField>
    <fullName>Grant_Application__c</fullName>
    <description>Grant Application master record</description>
    <inlineHelpText>Grant Application master record parent</inlineHelpText>
    <label>Grant Application</label>
    <referenceTo>GGW_Grant_Application__c</referenceTo>
    <relationshipLabel>Selected Items</relationshipLabel>
    <relationshipName>Selected_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/default/objects/GGW_Selected_Item__c/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <formula>GGW_Section__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Section Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Selected_Block__c.field-meta.xml
<CustomField>
    <fullName>Selected_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to a chose text block for section to use in Grant application</description>
    <inlineHelpText>Link to a chose text block for section to use in Grant application</inlineHelpText>
    <label>Selected Block</label>
    <referenceTo>GGW_Content_Block__c</referenceTo>
    <relationshipLabel>Selected Items</relationshipLabel>
    <relationshipName>Selected_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/default/objects/GGW_Selected_Item__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GGW_Selected_Item__c/fields/Text_Block__c.field-meta.xml
<CustomField>
    <fullName>Text_Block__c</fullName>
    <description>Formatted rich text holds a copy of block of content or new content for editing and grant.</description>
    <inlineHelpText>Formatted rich text holds a copy of block of content or new content for editing and grant.</inlineHelpText>
    <label>Text Block</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/GGW_Util.cls
/**
 * GGW_Util class for support utility methods on Grant application.
 * Used by standard and Custom controller
 * 
 * @author Igor Androsov
 * @version 1.0
 */
public class GGW_Util {
    // Pass Grant application ID record
    // return a list of selected Items (sections+blocks)
    public static List<GGW_Selected_Item__c> getSelectedItems(String appId) {
        system.debug('### Grant ID:'+appId);
        List<GGW_Selected_Item__c> items = new List<GGW_Selected_Item__c>();
        items = [SELECT Id, Name, Application_Name__c, Grant_Application__c, Selected_Block__c, 
                        GGW_Section__c, Section_Name__c, Text_Block__c,  Sort_Order__c
                        FROM GGW_Selected_Item__c WHERE Grant_Application__c =: appId ORDER BY Sort_Order__c];
        return items;
    }
}