force-app/main/default/default/objects/GGW_Grant_Application__c/GGW_Grant_Application__c.object-meta.xml
<CustomObject>
    <description>Main header object to manage and create Grant applications and related content</description>
    <label>Grant Application</label>
    <nameField>
        <label>GGW Grant Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/n/GGW_Grant_Editor?c__recordId=&quot; &amp; Id, Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describe a grant in short text with 255 characters</description>
    <inlineHelpText>Describe a grant in short text with 255 characters</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/DistributionPublicUrl__c.field-meta.xml
<CustomField>
    <fullName>DistributionPublicUrl__c</fullName>
    <description>Distribution URL</description>
    <inlineHelpText>Distribution URL</inlineHelpText>
    <label>DistributionPublicUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Include_Logo__c.field-meta.xml
<CustomField>
    <fullName>Include_Logo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This boolean TRU/FALSE field indicates if log be included or not in final application</description>
    <inlineHelpText>This boolean TRU/FALSE field indicates if log be included or not in final application</inlineHelpText>
    <label>Include Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language_Support</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Logo_Download_Url__c.field-meta.xml
<CustomField>
    <fullName>Logo_Download_Url__c</fullName>
    <description>URL for public image download used for LWC or page display</description>
    <inlineHelpText>URL for public image download used for LWC or page display</inlineHelpText>
    <label>Logo Download Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GGW_Grant_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Language_Support.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <description>Supported languages to switch</description>
    <masterLabel>Language Support</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GGW_ApplicationSelector.cls
/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 * 
 * GGW_ApplicationSelector SOQL Query class support GGW.
 * 
 */
public with sharing class GGW_ApplicationSelector {
    public static List<GGW_Grant_Application__c> getGrantApplications(){
        return [SELECT Id, Name, Application_Name__c, Logo_Download_Url__c, 
                        DistributionPublicUrl__c, Status__c, Description__c, 
                        Language__c, Include_Logo__c  
                FROM GGW_Grant_Application__c 
                WITH SECURITY_ENFORCED];
    }

    public static GGW_Grant_Application__c queryGrantApp(String appId){
        return [SELECT Id, Name, Application_Name__c, Logo_Download_Url__c, 
                        DistributionPublicUrl__c, Status__c, Description__c, 
                        Language__c, Include_Logo__c  
                FROM GGW_Grant_Application__c 
                WHERE Id =: appId WITH SECURITY_ENFORCED LIMIT 1];
    }

}